import React, { useEffect, useState } from 'react';
import type { Question } from '../../types/Question';
import '../../styles/print.css';

const PrintView: React.FC = () => {
    const [questions, setQuestions] = useState<Question[]>([]);
    const [showAnswers, setShowAnswers] = useState(false);
    const [examTitle, setExamTitle] = useState('Exam');
    const [branding] = useState({
        logoUrl: 'https://examify.web.app/web-app-manifest-512x512.png',
        primaryColor: '#0d6efd'
    });

    useEffect(() => {
        // 1. Get configuration from URL
        const params = new URLSearchParams(window.location.search);
        const showAnswersParam = params.get('showAnswers') === 'true';
        setShowAnswers(showAnswersParam);

        // 2. Get data from LocalStorage
        const storedData = localStorage.getItem('examify-print-data');
        if (storedData) {
            try {
                const parsedData = JSON.parse(storedData);
                setQuestions(parsedData);
            } catch (error) {
                console.error("Failed to parse print data", error);
            }
        }

        const storedTitle = localStorage.getItem('examify-print-title');
        if (storedTitle) {
            setExamTitle(storedTitle);
        }

        // 3. Trigger print after a short delay to ensure rendering
        // Increased delay slightly to ensure images/styles load
        const timer = setTimeout(() => {
            window.print();
        }, 800);

        return () => clearTimeout(timer);
    }, []);

    const currentDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });

    return (
        <div className="print-container">
            {/* Header */}
            <div className="print-header">
                <div className="d-flex align-items-center">
                    <a href="https://examify.web.app" target="_blank" rel="noopener noreferrer" className="text-decoration-none text-dark d-flex align-items-center">
                        <img src={branding.logoUrl} alt="Logo" className="print-logo me-3" />
                        <div>
                            <h1 className="print-title">{examTitle}</h1>
                            <div className="text-muted small">Generated by Examify</div>
                        </div>
                    </a>
                </div>
                <div className="print-meta">
                    <div><strong>Date:</strong> {currentDate}</div>
                    <div><strong>Questions:</strong> {questions.length}</div>
                </div>
            </div>

            {/* Questions List */}
            <div className="questions-list">
                {questions.map((q) => (
                    <div key={q.id} className="question-card">
                        <div className="d-flex mb-3">
                            <div className="question-number">Q{q.question_number}.</div>
                            <div className="flex-grow-1 question-text">
                                <div dangerouslySetInnerHTML={{ __html: q.question_text }} />
                            </div>
                        </div>

                        <div className="options ms-4 mb-3">
                            {Object.entries(q.options).map(([key, value]) => (
                                <div key={key} className="option-item">
                                    <span className="option-badge text-uppercase">{key}</span>
                                    <div className="flex-grow-1" dangerouslySetInnerHTML={{ __html: value }} />
                                </div>
                            ))}
                        </div>

                        {showAnswers && (
                            <div className="answer-section">
                                <div className="mb-2">
                                    <strong>Correct Answer: </strong>
                                    <span className="correct-answer text-uppercase">{q.correct_answer}</span>
                                </div>
                                {q.explanation && (
                                    <div>
                                        <strong>Explanation:</strong>
                                        <div className="mt-1 text-muted small" dangerouslySetInnerHTML={{ __html: q.explanation }} />
                                    </div>
                                )}
                            </div>
                        )}
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="print-footer">
                <div>{examTitle}</div>
                <div>
                    <a href="https://examify.web.app" target="_blank" rel="noopener noreferrer">
                        Examify - The Ultimate Exam Preparation Tool
                    </a>
                </div>
                {/* <div>Page <span className="page-number"></span></div> */}
            </div>
        </div>
    );
};

export default PrintView;
